import random 

powerful_quotes = [
    "The only way to do great work is to love what you do. – Steve Jobs",
    "The purpose of our lives is to be happy. – Dalai Lama",
    "Life is what happens when you’re busy making other plans. – John Lennon",
    "Get busy living or get busy dying. – Stephen King",
    "You only live once, but if you do it right, once is enough. – Mae West",
    "Many of life’s failures are people who did not realize how close they were to success when they gave up. – Thomas A. Edison",
    "If you want to live a happy life, tie it to a goal, not to people or things. – Albert Einstein",
    "Never let the fear of striking out keep you from playing the game. – Babe Ruth",
    "Money and success don’t change people; they merely amplify what is already there. – Will Smith",
    "Your time is limited, don’t waste it living someone else’s life. – Steve Jobs",
    "Not how long, but how well you have lived is the main thing. – Seneca",
    "If life were predictable it would cease to be life, and be without flavor. – Eleanor Roosevelt",
    "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it. – Henry Ford",
    "In order to write about life first you must live it. – Ernest Hemingway",
    "The big lesson in life, baby, is never be scared of anyone or anything. – Frank Sinatra",
    "Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth. – Mark Twain",
    "Curiosity about life in all of its aspects, I think, is still the secret of great creative people. – Leo Burnett",
    "Life is not a problem to be solved, but a reality to be experienced. – Soren Kierkegaard",
    "The unexamined life is not worth living. – Socrates",
    "Turn your wounds into wisdom. – Oprah Winfrey",
    "The way I see it, if you want the rainbow, you gotta put up with the rain. – Dolly Parton",
    "Do all the good you can, for all the people you can, in all the ways you can, as long as you can. – Hillary Clinton",
    "Don’t settle for what life gives you; make life better and build something. – Ashton Kutcher",
    "Everything negative – pressure, challenges – is all an opportunity for me to rise. – Kobe Bryant",
    "I like criticism. It makes you strong. – LeBron James",
    "You never really learn much from hearing yourself speak. – George Clooney",
    "Life is really simple, but men insist on making it complicated. – Confucius",
    "Life is a succession of lessons which must be lived to be understood. – Helen Keller",
    "My mama always said, life is like a box of chocolates. You never know what you’re gonna get. – Forrest Gump",
    "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny. – Lao-Tze",
    "When we do the best we can, we never know what miracle is wrought in our life or in the life of another. – Helen Keller",
    "The healthiest response to life is joy. – Deepak Chopra",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. – Albert Einstein",
    "Life is a flower of which love is the honey. – Victor Hugo",
    "Keep smiling, because life is a beautiful thing and there’s so much to smile about. – Marilyn Monroe",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship. – Buddha",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. – Dr. Seuss",
    "Good friends, good books, and a sleepy conscience: this is the ideal life. – Mark Twain",
    "Life would be tragic if it weren’t funny. – Stephen Hawking",
    "Live in the sunshine, swim the sea, drink the wild air. – Ralph Waldo Emerson",
    "The greatest pleasure of life is love. – Euripides",
    "Life is what we make it, always has been, always will be. – Grandma Moses",
    "Life’s tragedy is that we get old too soon and wise too late. – Benjamin Franklin",
    "Life is about making an impact, not making an income. – Kevin Kruse",
    "I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game-winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed. – Michael Jordan",
    "Every strike brings me closer to the next home run. – Babe Ruth",
    "To live is the rarest thing in the world. Most people exist, that is all. – Oscar Wilde",
    "To live is to suffer, to survive is to find some meaning in the suffering. – Friedrich Nietzsche",
    "Life is never fair, and perhaps it is a good thing for most of us that it is not. – Oscar Wilde",
    "The only impossible journey is the one you never begin. – Tony Robbins",
    "In this life, when you deny someone an apology, you will remember it at time you beg forgiveness. – Toba Beta",
    "Life is ten percent what happens to us and ninety percent how we respond to it. – Charles R. Swindoll",
    "The more you praise and celebrate your life, the more there is in life to celebrate. – Oprah Winfrey",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. – Steve Jobs",
    "My life is my message. – Mahatma Gandhi",
    "Life is short, and it is up to you to make it sweet. – Sarah Louise Delany",
    "Don’t cry because it’s over, smile because it happened. – Dr. Seuss",
    "Life shrinks or expands in proportion to one’s courage. – Anaïs Nin",
    "Life is a daring adventure or nothing at all. – Helen Keller",
    "The most important thing is to enjoy your life – to be happy – it’s all that matters. – Audrey Hepburn",
    "I enjoy life when things are happening. I don’t care if it’s good things or bad things. That means you’re alive. – Joan Rivers",
    "Life is short, but it is wide. This too shall pass. – Rebecca Wells",
    "Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor. – Sholom Aleichem",
    "Live life to the fullest, and focus on the positive. – Matt Cameron",
    "Keep calm and carry on. – Winston Churchill",
    "Maybe that’s what life is… a wink of the eye and winking stars. – Jack Kerouac",
    "Life is a game and true love is a trophy. – Rufus Wainwright",
    "Life is too important to be taken seriously. – Oscar Wilde",
    "Live in the present and make it beautiful. – Roy T. Bennett",
    "Life’s too mysterious to take too serious. – Mary Engelbreit",
    "The purpose of life is to believe, to hope, and to strive. – Indira Gandhi",
    "The best way to prepare for life is to begin to live. – Elbert Hubbard",
    "Life is really generous to those who pursue their personal legend. – Paulo Coelho",
    "The good life is one inspired by love and guided by knowledge. – Bertrand Russell",
    "Life’s most persistent and urgent question is, ‘What are you doing for others?’ – Martin Luther King Jr.",
    "You get in life what you have the courage to ask for. – Oprah Winfrey",
    "Life is inherently risky. There is only one big risk you should avoid at all costs, and that is the risk of doing nothing. – Denis Waitley",
    "The quality of a person’s life is in direct proportion to their commitment to excellence, regardless of their chosen field of endeavor. – Vince Lombardi",
    "Life doesn’t require that we be the best, only that we try our best. – H. Jackson Brown Jr.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations. – Oliver Goldsmith",
    "The true secret of happiness lies in taking a genuine interest in all the details of daily life. – William Morris",
    "The purpose of life, after all, is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience. – Eleanor Roosevelt",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. – Maya Angelou",
    "Life is short, and it’s up to you to make it sweet. – Sadie Delany",
]


quote = random.choice(powerful_quotes)
print(quote)